### ISSUE TITLE
.update_tree() error value too long for type character varying(500)

### ISSUE THREAD

**Issue by aldarund** [fabiocaccamo/django-treenode#12]
treenode tries to set tn_siblings_pks and its could be longer than 500 charts. And thast only with 157 records in my table, where all of them root level

update data
```
{'tn_siblings_pks': '2,5,46,18,62,142,158,13,40,11,135,51,23,66,6,74,31,98,17,104,19,118,105,83,30,90,15,56,137,54,96,125,148,58,26,50,89,35,29,108,36,86,153,57,87,25,78,84,77,20,85,41,45,44,81,73,109,150,92,37,12,110,48,151,99,133,43,128,103,146,61,156,65,32,155,131,141,42,75,97,34,119,55,64,95,116,147,113,157,106,59,28,126,144,139,132,60,152,9,136,7,107,134,80,33,101,114,121,88,120,49,145,123,22,63,127,79,21,138,24,100,14,129,143,4,3,93,140,154,16,27,47,68,69,71,72,76,82,91,111,67,117,149,10,122,8,53,52,94,124,70,112,39,102,115,130,38', 'tn_siblings_count': 157, 'tn_order': 117, 'tn_index': 117}
```
```
Traceback (most recent call last):
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(500)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\treenode\models.py", line 367, in update_tree
    cls.objects.filter(pk=obj_pk).update(**obj_data)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\raven\contrib\django\client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\back\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(500)
```

that kind of make lib unusable

**Comment by fabiocaccamo** [comment]
@aldarund you are using an old version of this package, please upgrade it to the latest version and run `python manage.py migrate`.

**Comment by aldarund** [comment]
Oopps, i missed to add it to apps, so migration wasnt applying.
